### ISSUE TITLE
Simplify .travis.yml

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [miniclip/eredis#12]
Have this working:
```
language: erlang
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.3
  - 23.0
services:
  - redis-server
script: make travis
```

**Comment by lrascao** [comment]
we should consider github actions as an alternative to Travis which seems to be on it's way out

**Comment by paulo-ferraz-oliveira** [comment]
We should, probably. Is there a readily available example for us to consider? Because otherwise we'll get stuck on doing something we don't yet know how to, instead of solving a present issue with something we know how to.

**Comment by paulo-ferraz-oliveira** [comment]
Potential reading:
* https://developer.okta.com/blog/2020/05/18/travis-ci-to-github-actions
* https://medium.com/@nwillc/travis-ci-to-github-actions-925d574f3f2b
